config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users
  resources :notices

  get 'families/register', to: 'families#register'
  post 'families/register', to: 'families#register_confirm'
  resources :families do 
    resources :members
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?
      if user.is_admin?
        can :manage, :all
      elsif user.is_family?
        can :manage, Member
        cannot :new, Member
      end
    end
    
    can :register, Family
    can :register_confirm, Family
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/family.rb
class Family < ApplicationRecord
  extend FriendlyId
  friendly_id :name

  has_many :members 

  belongs_to :user, :dependent => :destroy, optional: true
end

app/models/member.rb
class Member < ApplicationRecord
  extend FriendlyId
  friendly_id :first_name

  belongs_to :family
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :family
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: "You do not have permission to access"
  end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  load_and_authorize_resource :find_by => :name

  before_action :set_family, only: [:edit, :update, :destroy]

  skip_before_action :authenticate_user!, :only => [:register, :register_confirm]

  # GET /families
  # GET /families.json
  def index
    @families = Family.all
  end

  # GET /families/1
  # GET /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
    # @family.build_user
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families
  # POST /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to families_path, notice: 'Family was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /families/1
  # PATCH/PUT /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to families_path, notice: 'Family was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_path, notice: 'Family was successfully destroyed.' }
    end
  end

  def register
    @passport_no = params[:passport_no]

    family = Family.find_by(passport_no: @passport_no)
    user = User.find(family.user_id) if family

    if family && !user
      render :register_confirm
    end

    if user
      flash[:alert] = "Passport no registered!"
    else
      flash[:error] = "#{@passport_no} not found!" if @passport_no
    end

  end

  def register_confirm

    user_params = params[:user]
    family = Family.find_by(passport_no: user_params["passport_no"])
    new_user = User.new(email: user_params["email"], password: user_params["password"], password_confirmation: user_params["password_confirmation"], is_family: user_params["is_family"]) 

    if new_user.save && family

      family.user_id = new_user.id
      family.save

      flash[:success] = "Register Success!"
      redirect_to root_path
    else

      flash[:error] = "Email or Password not correct!"
      redirect_to families_register_path
    end


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_params
      params.require(:family).permit(:passport_no, :name, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]

  def index
    @notices = Notice.all
    if current_user.present?
      if current_user.is_family
        @family = current_user.family
        redirect_to family_members_path(@family)
      end
    end
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  load_and_authorize_resource :find_by => :first_name

  before_action :set_member, only: [:edit, :update, :destroy]
  before_action :set_family

  # GET /members
  # GET /members.json
  def index
    @members = Member.where(family_id: @family.id)
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    @member.family_id = @family.id

    respond_to do |format|
      if @member.save
        format.html { redirect_to family_members_new_url, notice: 'Member was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to family_members_new_url, notice: 'Member was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to family_members_new_url, notice: 'Member was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.friendly.find(params[:id])
    end

    def set_family
      @family = Family.friendly.find(params[:family_id])
    end

    def family_members_new_url
      family_members_path(@family)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :visa_exp, :wp_exp, :noti90, :passport_exp, :doe, :dob)
    end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  load_and_authorize_resource

  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to notices_path, notice: 'Notice was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to notices_path, notice: 'Notice was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_path, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/families/_form.html.erb
<%= bootstrap_form_with(model: family, local: true, url: url) do |form| %>

  <%= form.text_field :passport_no %>
  <%= form.text_field :name %>
  <%= form.text_field :phone %>
  <%= form.submit %>

<% end %>

app/views/families/edit.html.erb
<h1>Editing Family</h1>

<%= render 'form', family: @family, url: family_path %>

<%= link_to 'Back', families_path, class: "btn btn-info" %>

app/views/families/index.html.erb
<div class="row manage-title">
  <div class="col-9"><h3>LIST</h3></div>
  <div class="col text-right"><%= link_to 'New Family', new_family_path, class: "btn btn-primary" %></div>
</div>

<% if !@families.present? %>
  <div class="col">NO DATA</div>
<% end %>

<div class="row">
<% @families.each do |family| %>
<div class="col-12">
  <div class="card">
    <h3 class="card-header">
      <%= link_to family.name, family_members_path(family), class: 'card-link' %>
    </h3>
    <div class="card-body">
      <p class="card-text"><%= family.passport_no %></p>
      <p class="card-text"><%= family.phone %></p>

      <hr>
      <div class="col text-right">
        <%= link_to 'Edit', edit_family_path(family), class: 'btn btn-warning' %>
        <%= link_to 'Destroy', family_path(family), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>

    </div>
  </div>  
</div>
<% end %>
</div>

app/views/families/new.html.erb
<h1>New Family</h1>

<%= render 'form', family: @family, url: families_path %>

<%= link_to 'Back', families_path, class: "btn btn-info" %>

app/views/families/register.html.erb
<h1>Register</h1>

<%= bootstrap_form_tag url: families_register_url, method: :get do |f| %>
  <%= f.text_field :passport_no %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back', families_path, class: "btn btn-info" %>

app/views/families/register_confirm.html.erb
<h1>Register</h1>
  
<%= bootstrap_form_with(model: User.new, url: families_register_path) do |f| %>

  <%= f.text_field :email %>
  <%= f.password_field :password %>
  <%= f.password_field :password_confirmation %>
  <%= f.hidden_field :is_family, value: true %>
  <%= f.hidden_field :passport_no, value: @passport_no %>

  <%= f.submit %>

<% end %>

<%= link_to 'Back', families_path, class: "btn btn-info" %>

app/views/home/index.html.erb
<div class="row">
  <div class="col-12 text-center">

    <div class="row">
      <div class="col-12">
        <h1> LOGO THAI VISA ADVISOR </h1>
      </div>

      <div class="col-12">
        <div class="card text-center">
          <div class="card-header">
            Notice
          </div>
          <div class="card-body">
            <div class="col text-left">
              <% @notices.each do |notice| %>
                <h5>
                  <%= fa_icon "location-arrow" %> <%= notice.message %>
                </h5>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <% if !user_signed_in? %>
        <div class="col-12">
          <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-dark' %>  
          <%= link_to 'Register', families_register_path, class: 'btn btn-outline-info' %>  
        </div>
      <% end %>

      <% if current_user && current_user.is_admin %>
        <%= link_to 'Manage Family', families_path, class: 'btn btn-outline-danger col-12' %>
        <%= link_to 'Manage Notice', notices_path, class: 'btn btn-outline-info col-12' %>  
      <% end %>
    </div>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThaiVisaAdvisor</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% unless flash.empty? %>
      <script type="text/javascript">
        <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
        toastr['<%= type %>']('<%= f[1] %>');
        <% end %>
      </script>
    <% end %>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    
      <div class="container">
        <a class="navbar-brand" href="/">Thai Visa Advisor</a>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-dark'  %>        
            </li>
          <% end %>
        </ul>
      </div>

    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/members/_form.html.erb
<% if member.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

    <ul>
    <% member.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= bootstrap_form_with(model: member, local: true, url: url) do |form| %>

  <%= form.text_field :first_name %>
  <%= form.text_field :last_name %>
  
  <% if !current_user.is_family %>
    <%= form.date_field :visa_exp %>
    <%= form.date_field :wp_exp %>
    <%= form.date_field :noti90 %>
    <%= form.date_field :passport_exp %>
  <% end %>

  <%= form.date_field :doe %>
  <%= form.date_field :dob %>

  <%= form.submit %>

<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member, url: family_member_path %>

<%= link_to 'Back', family_members_path, class: "btn btn-info" %>

app/views/members/index.html.erb
<div class="row manage-title">
  <div class="col"><h1>Family: <%= @family.name %></h1></div>
  <div class="col text-right">
    <% if can? :new, @member %>
      <%= link_to 'New Member', new_family_member_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<% if !@members.present? %>
  <div class="col">NO DATA</div>
<% end %>

<div class="row">
<% @members.each_with_index do |member, index| %>
<div class="col-12">
  <div class="card">
    <h5 class="card-header">
      <div class="row">
        <div class="col-9">
          <%= member.first_name %> <%= member.last_name %>
        </div>
        <div class="col text-right">
          <button class='btn btn-info' onclick="toggle(this)">
            <%= fa_icon  index > 0 ? "chevron-down" : "chevron-up" %>
          </button>
        </div>
      </div>
    </h5>
    <div class="card-body <%= index > 0 && 'hidden'%>">

      <div class="row">
        <h6 class="card-text col-4">visa_exp: <%= member.visa_exp || '-' %></h6>
        <h6 class="card-text col-4">wp_exp: <%= member.wp_exp || '-' %></h6>
        <h6 class="card-text col-4">noti90: <%= member.noti90 || '-'%></h6>
        <h6 class="card-text col-4">passport_exp: <%= member.passport_exp || '-'%></h6>
        <h6 class="card-text col-4">passport_exp: <%= member.passport_exp || '-'%></h6>
        <h6 class="card-text col-4">doe: <%= member.doe || '-'%></h6>
        <h6 class="card-text col-4">dob: <%= member.dob || '-'%></h6>
      </div>

      <hr>
      <div class="col text-right">
        <%= link_to 'Edit', edit_family_member_path(@family, member), class: 'btn btn-warning' %>
        <%= link_to 'Destroy', family_member_path(@family, member), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>

    </div>
  </div>
</div>
<% end %>
</div>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member, url: family_members_path %>

<%= link_to 'Back', family_members_path, class: "btn btn-info" %>

app/views/notices/_form.html.erb
<%= bootstrap_form_with(model: notice, local: true) do |form| %>

  <%= form.text_field :message %>
  <%= form.submit %>

<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Back', notices_path, class: "btn btn-info" %>

app/views/notices/index.html.erb
<div class="row manage-title">
  <div class="col"><h1>Notice</h1></div>
  <div class="col text-right"><%= link_to 'New Notice', new_notice_path, class: "btn btn-primary" %></div>
</div>

<% if !@notices.present? %>
  <div class="col">NO DATA</div>
<% end %>

<div class="row">
<% @notices.each do |notice| %>
<div class="col-12">
  <div class="card">
    <h3 class="card-header">
      <%= notice.message %>
    </h3>
    <div class="card-body">
      <h6 class="card-subtitle mb-2 text-muted">Create At: <%= notice.created_at %></h6>
      <p class="card-text">Update At: <%= notice.updated_at %></p>

      <hr>
      <div class="col text-right">
        <%= link_to 'Edit', edit_notice_path(notice), class: 'btn btn-warning' %>
        <%= link_to 'Destroy', notice, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      
    </div>
  </div>
</div>
<% end %>
</div>

app/views/notices/new.html.erb
<h1>New Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Back', notices_path, class: "btn btn-info" %>